# Example Home Assistant configuration for the Liebe Dashboard
# Add this to your configuration.yaml

panel_custom:
  - name: liebe-dashboard-panel
    sidebar_title: Liebe Dashboard
    sidebar_icon: mdi:view-dashboard
    url_path: liebe
    module_url: /local/liebe-dashboard/custom-panel.js
    config:
      # Any custom configuration can go here
      theme: default