/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelIndexRouteImport } from './routes/panel-index'
import { Route as TestStoreRouteImport } from './routes/test-store'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelIndexRouteImport } from './routes/panel.index'

const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/panel-index',
  path: '/panel-index',
  getParentRoute: () => rootRouteImport,
} as any)
const TestStoreRoute = TestStoreRouteImport.update({
  id: '/test-store',
  path: '/test-store',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/panel/',
  path: '/panel/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$slug': typeof SlugRoute
  '/panel-index': typeof PanelIndexRoute
  '/test-store': typeof TestStoreRoute
  '/panel': typeof PanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$slug': typeof SlugRoute
  '/panel-index': typeof PanelIndexRoute
  '/test-store': typeof TestStoreRoute
  '/panel': typeof PanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$slug': typeof SlugRoute
  '/panel-index': typeof PanelIndexRoute
  '/test-store': typeof TestStoreRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/$slug' | '/panel-index' | '/test-store' | '/panel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/$slug' | '/panel-index' | '/test-store' | '/panel'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$slug'
    | '/panel-index'
    | '/test-store'
    | '/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  SlugRoute: typeof SlugRoute
  PanelIndexRoute: typeof PanelIndexRoute
  TestStoreRoute: typeof TestStoreRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel-index': {
      id: '/panel-index'
      path: '/panel-index'
      fullPath: '/panel-index'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-store': {
      id: '/test-store'
      path: '/test-store'
      fullPath: '/test-store'
      preLoaderRoute: typeof TestStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  SlugRoute: SlugRoute,
  PanelIndexRoute: PanelIndexRoute,
  TestStoreRoute: TestStoreRoute,
  PanelIndexRoute: PanelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
